Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,4 +1,4 @@
-name: DEPLOYMENT WORKFLOW
+name: DEPLOYMENT WORKFLOW V1
 run-name: Deploy branch ${{ github.ref_name }} to production
 
 on:
@@ -11,6 +11,7 @@ on:
 
 permissions:
   contents: read
+
 concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
   cancel-in-progress: true
@@ -19,27 +20,23 @@ jobs:
   cleanup:
     runs-on: self-hosted
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
-        
       - name: Clean up temporary files
         run: |
           echo "Started cleaning up temporary files..."
-          rm -rf /home/ubuntu/actions-runner/viet-travel/viet-travel-fe/viet-travel-fe/dist/viet-travel-fe/*
+          sudo rm -rf /home/ubuntu/actions-runner/viet-travel/viet-travel-fe/dist/*
 
   build-n-deploy:
     runs-on: self-hosted
     needs: cleanup
     env:
-      BUILD_FOLDER: /home/ubuntu/actions-runner/viet-travel/viet-travel-fe/viet-travel-fe/dist/viet-travel-fe
+      BUILD_FOLDER: /home/ubuntu/actions-runner/viet-travel/viet-travel-fe/dist
       DEPLOY_PATH: /var/www/viet-travel-fe
-      NEW_FILE_NAME: fe-build
     steps:
-      - name: Checkout branch ${{ github.event.inputs.branch }}
+      - name: Checkout branch
         uses: actions/checkout@v4
         with:
-          ref: ${{ github.event.inputs.branch }}
-        
+          ref: ${{ github.inputs.branch }}
+
       - name: Set up Node.js
         uses: actions/setup-node@v3
         with:
@@ -50,6 +47,7 @@ jobs:
 
       - name: Build the project
         run: |
+          set -e  # Exit on error
           export NODE_OPTIONS=--max-old-space-size=4096
           npm run build:prod --verbose
 
@@ -58,21 +56,23 @@ jobs:
           echo "Listing files in build directory:"
           ls -la $BUILD_FOLDER
 
-      - name: Create deploy folder
+      - name: Deploy to server
         run: |
+          echo "Deploying files..."
           sudo mkdir -p $DEPLOY_PATH
           sudo cp -r $BUILD_FOLDER/* $DEPLOY_PATH
+          echo "Deployment completed."
 
-      - name: Verify copied files
+      - name: Verify deployment
         run: |
           echo "Listing files in $DEPLOY_PATH:"
           ls -la $DEPLOY_PATH
 
-      - name: Upload stubs to server
+      - name: Upload build artifacts
         uses: actions/upload-artifact@v4
         with:
           name: viettravelfe
-          path: target/${{ env.NEW_FILE_NAME }}
+          path: $BUILD_FOLDER
           if-no-files-found: warn
           compression-level: 6
           overwrite: false
